# ##################################
# KULED Light Switch, Model KS-602S
# ##################################
# D3 GPIO0: button (inverted)
# D6 GPIO12: relay + red led 
# D7 GPIO13: green led (inverted)
# ##################################


substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: kuled_ks_602s
  friendly_name: KuLED KS-602S
  ip_address: !secret kuled_ks_602s_ip
  icon: "mdi:ceiling-light"


esphome:
  # https://esphome.io/components/esphome
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m


wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1


# web_server:
#   port: 80
#   # https://esphome.io/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota


# # Disables use of Green LED
# status_led: 
#   # https://esphome.io/components/status_led
#   pin:
#     number: GPIO13
#     inverted: True


binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin:
      number: GPIO0
      inverted: True
    id: button
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: relay
    internal: True


switch:
  - platform: gpio
    # https://esphome.io/components/switch/gpio
    name: ${friendly_name} Green LED
    id: green_led
    pin:
      number: GPIO13
      inverted: True
    internal: True

  - platform: gpio
    # https://esphome.io/components/switch/gpio
    pin: GPIO12
    name: ${friendly_name}
    id: relay
    icon: ${icon}
    # Tie Green LED operation to relay
    on_turn_on:
      - switch.turn_off: green_led
    on_turn_off:
      - switch.turn_on: green_led
